- name: Create admin user
  user:
    name: "{{ admin_user }}"
    comment: "Administrator account"
    state: present
    groups: "{{ admin_groups }}"
    shell: /bin/bash
    append: yes

- name: Deploy admin's ssh public key
  authorized_key:
    user: "{{ admin_user }}"
    key: "{{ admin_ssh_pub_key }}"

- name: Create Docker user
  user:
    name: "{{ docker_user }}"
    comment: "Docker user"
    state: present
    groups: "{{ docker_user_groups }}"
    shell: /bin/bash
    append: yes
    generate_ssh_key: yes

- name: Add Docker's public key to authorized keys
  shell: "cat /home/{{ docker_user }}/.ssh/id_rsa.pub >> /home/{{ docker_user }}/.ssh/authorized_keys"
