---
# DO API settings
do_client_id: ~
do_api_key: ~

# DO SSH key settings
do_ssh_name: fitme-ansible
do_ssh_pub_key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
do_ssh_private_key: "~/.ssh/id_rsa"

# DO droplet settings
do_region: fra1
do_size: 2gb
do_image: "ubuntu-16-04-x64"

# SSH
ssh_port: 22
ssh_groups: "sudo docker"

# System admin to create
admin_user: "administrator"
admin_groups: "sudo"
admin_ssh_pub_key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

# Docker user that will launch the containers
docker_user: "docker"
docker_user_groups: "docker"

# UFW
ufw_allow_ports:
  - 22
  - 80
  - 443
  - 2375
  - 2376

# Swap settings
swapfile_location: /swapfile
swapfile_size: 4G
swapfile_swappiness: 10
swapfile_vfs_cache_pressure: 50
