- hosts: localhost
  connection: local
  vars_files:
    - ../config/default.yml
    - ../config/custom.yml
  vars_prompt:
    - name: do_name
      prompt: "Name the server that will host the environment"
      private: no
  tasks:
    - name: Register SSH key
      digital_ocean:
        state: present
        command: ssh
        name: "{{ do_ssh_name }}"
        ssh_pub_key: "{{ do_ssh_pub_key }}"
        api_token: "{{ do_api_token }}"
      register: do_droplet
      when: do_ssh_key_id is not defined

    - name: Register Droplet
      digital_ocean:
        state: active
        command: droplet
        name: "{{ do_name }}"
        region_id: "{{ do_region }}"
        size_id: "{{ do_size }}"
        image_id: "{{ do_image }}"
        ssh_key_ids: "{{ do_ssh_key_id }}"
        unique_name: yes
        private_networking: yes
        api_token: "{{ do_api_token }}"
        wait_timeout: 600
      register: do_droplet

    - debug: msg="IP of {{ do_name }} is {{ do_droplet.droplet.ip_address }}"

    - name: Wait for SSH connection
      wait_for:
        host: "{{ do_droplet.droplet.ip_address }}"
        port: 22
        timeout: 320
        state: started

    - debug: msg="SSH service of {{ do_name }} is available"    

    - name: Add new droplet to inventory
      add_host:
        name: "{{ do_name }}"
        groups: dohosts
        ansible_python_interpreter: /usr/bin/python3
        ansible_ssh_host: "{{ do_droplet.droplet.ip_address }}"
        ansible_ssh_user: root
        ansible_ssh_private_key_file: "{{ do_ssh_private_key }}"

- hosts: dohosts
  vars_files:
    - ../config/default.yml
    - ../config/custom.yml
  tasks:
    - import_tasks: ../tasks/swap.yml
    - import_tasks: ../tasks/software.yml
    - import_tasks: ../tasks/security.yml
    - import_tasks: ../tasks/users.yml

  handlers:
    - import_tasks: ../handlers/site.yml
